### ISSUE TITLE
Adding it to official myMPD repo?

### ISSUE THREAD

**Issue by jcorporation** [loop333/mympd_lastfm_scrobbler#2]
Any interest in adding this to the official myMPD repo?

**Comment by loop333** [comment]
sure, it would be nice

**Comment by jcorporation** [comment]
Here is it: https://github.com/jcorporation/mympd-scripts/tree/main/last.fm

**Comment by loop333** [comment]
thanks for adding )

**Comment by jcorporation** [comment]
Thanks for writing this scrobbler ;)
